name: CI on Commit
on: [push] # Triggers on every push to any branch

jobs:
  build:
    env:
      MIX_ENV: prod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          path: '.'

      - name: where am i
        run: pwd && ls -la

      - name: Nodejs setup
        run: cd assets && yarn install && cd ..
      - name: Setup
        run: mix deps.get --only prod &&
          mix compile &&
          mix assets.deploy

      - name: Generate release
        run: mix phx.gen.release --docker
  deploy:
    needs: build
    env:
      MIX_ENV: prod
    runs-on: self-hosted
    steps:
      - name: Run migrations
        run: docker exec stamp-map ./bin/migrate

      - name: Restart service
        run: cd $HOME/server && docker compose restart stamp-map --build
